# Base on offical Node.js Alpine image
FROM node:14.17

# Set working directory
WORKDIR /usr/app

COPY ./package*.json ./

# Install dependencies
RUN npm install --production

# Copy all files
COPY ./ ./
RUN mv .env.production .env
# Build app
RUN npm run prod

# Expose the listening port
EXPOSE 3000

# Run container as non-root (unprivileged) user
# The node user is provided in the Node.js Alpine base image
USER node

# Run npm start script when container starts
CMD [ "npm", "start" ]



